##############################################################################
# Starship 設定
#
# https://starship.rs/config/
##############################################################################

# starshipが現在のディレクトリ下のファイルをチェックするまで10ミリ秒待ちます
scan_timeout = 10
command_timeout = 250
# プロンプトの先頭での改行を有効にする
add_newline = true

[hostname]
ssh_only = true
format = "[$hostname:](bold blue) "
disabled = false

# パス名 ｜ 省略表示にされないようにする
[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = ".../"

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
# docker開発環境で応答が遅すぎるときに true にすると速くなる
# disabled = true
format = '([\[$all_status $ahead_behind\]]($style) )'
style = "blue"

# status系
staged = '[+${count}](green)'
modified = '[!${count}](yellow)'
deleted = "[✘${count}](red)"

# ahead_behind系
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

# [git_metrics]
# disabled = false
# format = '([+$added]($added_style)/)([-$deleted]($deleted_style) )'

[character]
success_symbol = "[❯](bold blue)"

# ----------------------------------------------------------------------------
# バージョン周り
# ----------------------------------------------------------------------------

[docker_context]
format = "[$symbol]($style) "

[package]
disabled = true

[nodejs]
disabled = true
format = "[$symbol($version )]($style)"
symbol = "⬢:"

[php]
disabled = true
format = "[$symbol($version )]($style)"
symbol = "🐘:"

[aws]
format = '[$profile]($style) '
symbol = "☁️:"
style = "bold 110"

[terraform]
format = "[$symbol$workspace]($style) "
symbol = "💠:"

[python]
# format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)'
format = '[${symbol}(${version} )(\($virtualenv\))]($style)'
style = "yellow"
symbol = "🐍:"
pyenv_version_name = true

[vagrant]
format = "[$symbol($version )]($style)"
symbol = "⍱:"

[cmd_duration]
format = "[took $duration](yellow)"
